name: Github Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Listing files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          git clone git@github:$GITHUB_REPOSITORY
          git checkout $GITHUB_SHA

      - name: Checkout files
        uses: actions/checkout@v1

      - name: Listing files after checking out
        run: |
          pwd
          ls -a

      - name: Simple Javascript Action
        id: simple-action
        uses: actions/hello-world-javascript-action@v1 # import actions from github
        with:
          who-to-greet: James
      - name: Log the time
        run: echo "${{ steps.simple-action.outputs.time }}"
