name: Github Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Listing files
        run: |
          pwd
          ls

      - name: Checkout files
        uses: actions/checkout@v1

      - name: Listing files after checking out
        run: |
          pwd
          ls

      - name: Simple Javascript Action
        id: simple-action
        uses: actions/hello-world-javascript-action@v1 # import actions from github
        with:
          who-to-greet: James
      - name: Log the time
        run: echo "${{ steps.simple-action.outputs.time }}"
