name: Hello World

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-18.04
    steps:
      - name: echo a Hello World string
        run: echo "Hello World"
      - name: check node version
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
        
